# KataParty Configuration, generated/updated by v${project.version}

# If you want to reset any setting to default, simply delete it entirely
# and the config will be regenerated, keeping your existing settings
# while defaulting the deleted ones. Any comments you've made, however,
# will be wiped, since there's no easy way to keep them.

# This is what should be at the start of a message to send to the opposite
# chat; global instead of party or vice-versa.
chat-filtering-swap: "[%chat-filtering-swap%]"

# Here, you can change the default settings for newly created parties.
# Some settings require permission nodes to be changed when creating
# the party.
party-defaults:
  teleports: [%party-defaults.teleports%]
  pvp: [%party-defaults.pvp%]
  inventory: [%party-defaults.inventory%]
  visible: [%party-defaults.visible%]

# Set to true to have empty parties automatically be disbanded. If
# you want to instead keep empty parties, set to false instead.
remove-empty-parties: [%remove-empty-parties%]

# Below, you can customize the messages that are sent/shown to players.
messages:
  party-member-inform: "[%messages.party-member-inform%]"
  party-introvert-inform: "[%messages.party-introvert-inform%]"
  party-already-exists: "[%messages.party-already-exists%]"
  party-does-not-exist: "[%messages.party-does-not-exist%]"
  not-in-party: "[%messages.not-in-party%]"
  missing-disband-permission: "[%messages.missing-disband-permission%]"
  party-teleports-disabled: "[%messages.party-teleports-disabled%]"
  member-teleported-to: "[%messages.member-teleported-to%]"
  member-teleported-from: "[%messages.member-teleported-from%]"
  member-teleport-disabled: "[%messages.member-teleport-disabled%]"
  player-not-member: "[%messages.player-not-member%]"
  player-not-found: "[%messages.player-not-found%]"
  shared-inventory-disabled: "[%messages.shared-inventory-disabled%]"
  chat-filtering-toggled: "[%messages.chat-filtering-toggled%]"
  chat-filtering-party: "[%messages.chat-filtering-party%]"
  chat-filtering-global: "[%messages.chat-filtering-global%]"
  create-gui-title: "[%messages.create-gui-title%]"
  create-create: "[%messages.create-create%]"
  create-cancel: "[%messages.create-cancel%]"
  create-name-taken: "[%messages.create-name-taken%]"
  manage-gui-title: "[%messages.manage-gui-title%]"
  manage-click-to-change: "[%messages.manage-click-to-change%]"
  manage-cannot-change: "[%messages.manage-cannot-change%]"
  manage-click-to-use: "[%messages.manage-click-to-use%]"
  manage-cannot-use: "[%messages.manage-cannot-use%]"
  manage-your-rank: "[%messages.manage-your-rank%]"
  manage-leave: "[%messages.manage-leave%]"
  manage-not-member: "[%messages.manage-not-member%]"
  manage-rename: "[%messages.manage-rename%]"
  manage-admin: "[%messages.manage-admin%]"
  manage-members: "[%messages.manage-members%]"
  manage-members-online: "[%messages.manage-members-online%]"
  manage-mods-online: "[%messages.manage-mods-online%]"
  manage-admins-online: "[%messages.manage-admins-online%]"
  manage-teleports-enabled: "[%messages.manage-teleports-enabled%]"
  manage-teleports-disabled: "[%messages.manage-teleports-disabled%]"
  manage-pvp-enabled: "[%messages.manage-pvp-enabled%]"
  manage-pvp-disabled: "[%messages.manage-pvp-disabled%]"
  manage-inventory-enabled: "[%messages.manage-inventory-enabled%]"
  manage-inventory-disabled: "[%messages.manage-inventory-disabled%]"
  manage-visibility-enabled: "[%messages.manage-visibility-enabled%]"
  manage-visibility-disabled: "[%messages.manage-visibility-disabled%]"
  manage-disband: "[%messages.manage-disband%]"
  manage-close: "[%messages.manage-close%]"
  manage-summon: "[%messages.manage-summon%]"
  manage-self-teleports-enabled: "[%messages.manage-self-teleports-enabled%]"
  manage-self-teleports-disabled: "[%messages.manage-self-teleports-disabled%]"
  rename-gui-title: "[%messages.rename-gui-title%]"
  rename-name-requirements: "[%messages.rename-name-requirements%]"
  members-gui-title: "[%messages.members-gui-title%]"
  members-return: "[%messages.members-return%]"
  members-missing-player-file: "[%messages.members-missing-player-file%]"
  members-yourself: "[%messages.members-yourself%]"
  members-rank: "[%messages.members-rank%]"
  members-promote-moderator: "[%messages.members-promote-moderator%]"
  members-demote-kick: "[%messages.members-demote-kick%]"
  members-promote-admin: "[%messages.members-promote-admin%]"
  members-demote-member: "[%messages.members-demote-member%]"
  members-demote-moderator: "[%messages.members-demote-moderator%]"
  members-online: "[%messages.members-online%]"
  members-teleports: "[%messages.members-teleports%]"
  members-alive: "[%messages.members-alive%]"
  list-gui-title: "[%messages.list-gui-title%]"
  list-invisible: "[%messages.list-invisible%]"
  list-members-online: "[%messages.list-members-online%]"
  list-pvp: "[%messages.list-pvp%]"
  list-teleports: "[%messages.list-teleports%]"
  list-inventory: "[%messages.list-inventory%]"
  list-join: "[%messages.list-join%]"
  list-member: "[%messages.list-member%]"
  list-admin: "[%messages.list-admin%]"
  teleport-gui-title: "[%messages.teleport-gui-title%]"
