
name: "KataParty"
version: ${project.version}
description: "A party chat plugin made for Katatunka"
#load: POSTWORLD
main: com.lb_stuff.kataparty.KataPartyPlugin
authors:
  - "Nicholas \"LB\" Braden"
website: http://dev.bukkit.org/bukkit-plugins/kataparty/
database: false
depend: ["EventFilterServices"]
#prefix: "\xa7bKataParty\xa7r"
softdepend: ["TagAPI"]
loadbefore: []
awareness:
- !@UTF8

commands:
  KataParty:
    description: "Display \xa7ainfo\xa7r about \xa7bKataParty"
    usage: "/<command>"
    permission: KataParty.info
    permission-message: "\xa7cYou do not have permission."
    aliases:
      - kp
      - kpi
      - kpinfo
      - kpv
      - kpver
      - kpversion
      - kata
      - katatunka
      - katatunkaparty
      - party
      - partychat
      - pc
  kptoggle:
    description: "Toggle \xa7bchat filtering\xa7r between \xa7byour party\xa7r and \xa7bglobal chat"
    usage: "/<command>"
    permission: KataParty.toggle
    permission-message: "\xa7cYou do not have permission."
  kpcreate:
    description: "\xa7aCreate\xa7r a \xa7bKataParty\xa7r via a \xa7bGUI"
    usage: "/<command> <KataParty-name>"
    permission: KataParty.create
    permission-message: "\xa7cYou do not have permission to create KataParties."
  kplist:
    description: "Show a \xa7bGUI\xa7r with a \xa7blist\xa7r of available \xa7bKataParties"
    usage: "/<command>"
    permission: KataParty.list
    permission-message: "\xa7cYou do not have permission to list KataParties."
  kpjoin:
    description: "\xa7aJoin\xa7r a \xa7bKataParty\xa7r by name instead of \xa7bvia /kplist"
    usage: "/<command> <KataParty-name>"
    permission: KataParty.join
    permission-message: "\xa7cYou do not have permission to join KataParties."
  kpmanage:
    description: "\xa7aManage\xa7r your \xa7bpersonal settings\xa7r, or the \xa7bparty-wide settings"
    usage: "/<command>"
    permission: KataParty.manage
    permission-message: "\xa7cYou do not have permission to manage your KataParty's settings."
  kpmembers:
    description: "\xa7bToggle\xa7r display of a \xa7bscoreboard\xa7r showing your \xa7bparty members"
    usage: "/<command>"
    permission: KataParty.scoreboard
    permission-message: "\xa7cYou do not have permission."
  kptp:
    description: "\xa7aTeleport\xa7r to someone \xa7bvia GUI\xa7r or username"
    usage: "/<command> [optional-username]"
    permission: KataParty.teleport.do
    permission-message: "\xa7cYou do not have permission to teleport to KataParty members."
  kpshare:
    description: "\xa7aOpen\xa7r the \xa7bshared inventory\xa7r for your \xa7bKataParty\xa7r"
    usage: "/<command>"
    permission: KataParty.inventory.use
    permission-message: "\xa7cYou do not have permission to access your KataParty's shared inventory."
  kpleave:
    description: "\xa7cLeave\xa7r the \xa7bKataParty\xa7b you are in instead of \xa7bvia /kpmanage"
    usage: "/<command>"
    permission: KataParty.leave
    permission-message: "\xa7cYou do not have permission to leave your KataParty."
  kpback:
    description: "\xa7aReturn\xa7r to the/a \xa7bKataParty\xa7b you were previously in."
    usage: "/<command> [optional-KataParty-name]"
    permission: KataParty.back.use
    permission-message: "\xa7cYou do not have permission."
  kppardon:
    description: "\xa7aPardon\xa7r a player you \xa7ckicked\xa7r from your \xa7bKataParty\xa7b."
    usage: "/<command> <player-name> [optional-KataParty-name-for-admins]"
    permission: KataParty.pardon
    permission-message: "\xa7cYou do not have permission."
  kpdisband:
    description: "\xa7cDisband\xa7r your \xa7bKataParty\xa7r instead of \xa7bvia /kpmanage"
    usage: "/<command>"
    permission: KataParty.disband
    permission-message: "\xa7cYou do not have permission to disband your KataParty."
  kpclose:
    description: "\xa7dForce a\xa7r \xa7bKataParty\xa7r \xa7dto close"
    usage: "/<command> <KataParty-name>"
    permission: KataParty.close
    permission-message: "\xa7cYou do not have permission to force-close KataParties."
  kpadmin:
    description: "\xa7dManage a specific\xa7r \xa7bKataParty\xa7r\xa7d's settings"
    usage: "/<command> <KataParty-name>"
    permission: KataParty.arbiter
    permission-message: "\xa7cYou do not have permission to edit the settings of other KataParties."
  kpreload:
    description: "\xa7dReload and regenerate the config file"
    usage: "/<command>"
    permission: KataParty.reload
    permission-message: "You do not have permission."

permissions:
  KataParty.*:
    description: "Gives access to all KataParty permissions (for admins)"
    children:
      KataParty.info: true
      KataParty.toggle: true
      KataParty.create: true
      KataParty.hide: true
      KataParty.seehidden: true
      KataParty.stick: true
      KataParty.list: true
      KataParty.join: true
      KataParty.leave: true
      KataParty.disband: true
      KataParty.manage: true
      KataParty.arbiter: true
      KataParty.reload: true
      KataParty.update-notify: true
      KataParty.teleport.*: true
      KataParty.inventory.*: true
      KataParty.invite.*: true
      KataParty.shared-health.*: true
      KataParty.shared-xp.*: true
      KataParty.smart-splash-potions.*: true
      KataParty.back.use: true
      KataParty.pardon: true
      KataParty.back.grace-periods.admin: true
      KataParty.scoreboard: true
    default: op
  KataParty.teleport.*:
    description: "Gives access to all teleportation features"
    children:
      KataParty.teleport.do: true
      KataParty.teleport.disallow: true
      KataParty.teleport.disable: true
  KataParty.inventory.*:
    description: "Gives access to all inventory features"
    children:
      KataParty.inventory.use: true
      KataParty.inventory.enable: true
  KataParty.invite.*:
    description: "Gives access to all invitiation ticket permissions"
    children:
      KataParty.invite.enforce: true
      KataParty.invite.create: true
      KataParty.invite.accept: true
  KataParty.shared-health.*:
    description: "Gives access to all shared health permissions"
    children:
      KataParty.shared-health.toggle: true
      KataParty.shared-health.contribute: true
  KataParty.shared-xp.*:
    description: "Gives access to all shared xp permissions"
    children:
      KataParty.shared-xp.contribute: true
      KataParty.shared-xp.benefit: true
  KataParty.smart-splash-potions.*:
    description: "Gives access to all smart splash potions permissions"
    children:
      KataParty.smart-splash-potions.contribute: true
      KataParty.smart-splash-potions.benefit: true
  KataParty.info:
    description: "See version/author infrmation about KataParty"
    default: true
  KataParty.toggle:
    description: "Toggle chat filtering for one's self"
    default: true
  KataParty.create:
    description: "Allows creation of a KataParty"
    default: true
  KataParty.hide:
    description: "Allows for hiding KataParties from the list"
    default: op
  KataParty.seehidden:
    description: "Allows for seeing hidden KataParties in the list"
    default: op
  KataParty.stick:
    description: "Allows to toggle the sticky setting for KataParties"
    default: op
  KataParty.list:
    description: "Allows viewing a list of KataParties"
    default: true
  KataParty.join:
    description: "Allows joining a KataParty"
    default: true
  KataParty.disband:
    description: "Allows closing of a KataParty by party admin"
    default: true
  KataParty.manage:
    description: "Allows management of a KataParty (features based on party rank)"
    default: true
  KataParty.arbiter:
    description: "Allows management of a KataParty bypassing party rank"
    default: op
  KataParty.teleport.do:
    description: "Allows teleporting to a willing KataParty member"
    default: true
  KataParty.teleport.disallow:
    description: "Allows preventing other KataParty members from teleporting to you"
    default: true
  KataParty.teleport.disable:
    description: "Allows disabling teleportaion for an entire KataParty (based on party rank or KataParty.arbiter)"
    default: true
  KataParty.inventory.use:
    description: "Allows access to the shared KataParty inventory"
    default: true
  KataParty.inventory.enable:
    description: "Allows enabling/disabling the shared KataParty inventory"
    default: op
  KataParty.invite.enforce:
    description: "Allows making a party invite-only"
    default: true
  KataParty.invite.create:
    description: "Allows creating invitation tickets"
    default: true
  KataParty.invite.accept:
    description: "Allows accepting invitation tickets"
    default: true
  KataParty.reload:
    description: "Allows use of the /kpreload command to reload and regenerate the config"
    default: op
  KataParty.update-notify:
    description: "Players with this permission are notified of updates to KataParty"
    default: op
  KataParty.shared-health.toggle:
    description: "Allows toggling shared health for a party"
    default: true
  KataParty.shared-health.contribute:
    description: "Allows a player to contribute to the party's overall hared health (or be excluded)"
    default: true
  KataParty.shared-xp.contribute:
    description: "Allows contributing shared xp to the rest of the party"
    default: true
  KataParty.shared-xp.benefit:
    description: "Allows benefitting from shared xp from other party members"
    default: true
  KataParty.smart-splash-potions.contribute:
    description: "Allows throwing potions that know what they're doing with their life"
    default: true
  KataParty.smart-splash-potions.benefit:
    description: "Allows players to benefit from potions that know what they're doing with their life"
    default: true
  KataParty.back.use:
    description: "Allows use of the /kpback command"
    default: true
  KataParty.back.grace-periods.default:
    description: "Default grace period for /kpback unless changed in config"
    default: true
  KataParty.back.grace-periods.admin:
    description: "Infinie grace period for /kpback unless changed in config"
    default: op
  KataParty.pardon:
    description: "Allows use of the /kppardon command"
    default: true
  KataParty.scoreboard:
    description: "Allows members to toggle a scoreboard showing all their members"
    default: true
