
name: "KataParty"
main: com.lb_stuff.kataparty.KataParty
version: 1.1.1
author: "Nicholas \"LB\" Braden"
description: "A party chat plugin made for Katatunka"

commands:
  kataparty:
    description: "Display info about KataParty"
    usage: "/kataparty"
    aliases:
      - kp
  kpcreate:
    description: "Create a KataParty"
    usage: "/kpcreate <KataParty-name>"
    permission: KataParty.create
    permission-message: "You don't have the KataParty.create permisson :("
    aliases:
      - katacreate
  kplist:
    description: "Show a list of available KataParties"
    usage: "/kplist"
    permission: KataParty.list
    permission-message: "You don't have the KataParty.list permission :\\"
    aliases:
      - katalist
  kpjoin:
    description: "Join a KataParty by name"
    usage: "/kpjoin <KataParty-name>"
    permission: KataParty.join
    permission-message: "You don't have the KataParty.join permission :'("
    aliases:
      - katajoin
  kpleave:
    description: "Leave the KataParty you are in"
    usage: "/kpleave"
    permission: KataParty.join
    permission-message: "You don't have the KataParty.join permission (required to leave)"
    aliases:
      - kataleave
  kpdisband:
    description: "Disband your KataParty if you have permission to"
    usage: "/kpdisband"
    permission: KataParty.disband
    permission-message: "You don't have the KataParty.disband permission >:)"
    aliases:
      - katadisband
  kpclose:
    description: "Force a KataParty to close (for admins)"
    usage: "/kpclose <KataParty-name>"
    permission: KataParty.close
    permission-message: "You don't have the KataParty.close permission >:("
    aliases:
      - kataclose
  kpmanage:
    description: "Manage your KataParty and its members"
    usage: "/kpmanage"
    permission: KataParty.manage
    permission-message: "You don't have the KataParty.manage permission :("
    aliases:
      - katamanage
  kpadmin:
    description: "Manage a specific KataParty and its members (for admins)"
    usage: "/kpadmin <KataParty-name>"
    permission: KataParty.admin
    permission-message: "You don't have the KataParty.admin permission >:\\"
    aliases:
      - kataadmin
  kptp:
    description: "Teleport to someone in your KataParty"
    usage: "/kptp"
    permission: KataParty.teleport.do
    permission-message: "You don't have the KataParty.teleport.do permission..."
    aliases:
      - katatp
  kpshare:
    description: "Open the shared inventory for your KataParty"
    usage: "/kpshare"
    permission: KataParty.inventory.use
    permission-message: "You don't have the KataParty.inventory.use permission..."
    aliases:
      - katashare

permissions:
  KataParty.*:
    description: "Gives access to all KataParty permissions (for admins)"
    children:
      KataParty.create: true
      KataParty.hide: true
      KataParty.seehidden: true
      KataParty.list: true
      KataParty.join: true
      KataParty.disband: true
      KataParty.manage: true
      KataParty.admin: true
      KataParty.teleport.*: true
      KataParty.inventory.*: true
    default: op
  KataParty.teleport.*:
    description: "Gives access to all teleportation features"
    children:
      KataParty.teleport.do: true
      KataParty.teleport.disallow: true
      KataParty.teleport.disable: true
  KataParty.inventory.*:
    description: "Gives access to all inventory features"
    children:
      KataParty.inventory.use: true
      KataParty.inventory.enable: true
  KataParty.create:
    description: "Allows creation of a KataParty"
    default: true
  KataParty.hide:
    description: "Allows for hiding KataParties from the list"
    default: op
  KataParty.seehidden:
    description: "Allows for seeing hidden KataParties in the list"
    default: op
  KataParty.list:
    description: "Allows viewing a list of KataParties"
    default: true
  KataParty.join:
    description: "Allows joining a KataParty"
    default: true
  KataParty.disband:
    description: "Allows closing of a KataParty by party admin"
    default: true
  KataParty.manage:
    description: "Allows management of a KataParty (features based on party rank)"
    default: true
  KataParty.admin:
    description: "Allows management of a KataParty bypassing party rank"
    default: op
  KataParty.teleport.do:
    description: "Allows teleporting to a willing KataParty member"
    default: true
  KataParty.teleport.disallow:
    description: "Allows preventing other KataParty members from teleporting to you"
    default: true
  KataParty.teleport.disable:
    description: "Allows disabling teleportaion for an entire KataParty (based on party rank or KataParty.admin)"
    default: true
  KataParty.inventory.use:
    description: "Allows access to the shared KataParty inventory"
    default: true
  KataParty.inventory.enable:
    description: "Allows enabling/disabling the shared KataParty inventory"
    default: op
