
name: "KataParty"
main: com.lb_stuff.kataparty.KataPartyPlugin
version: ${project.version}
authors:
  - "Nicholas \"LB\" Braden"
description: "A party chat plugin made for Katatunka"
website: http://dev.bukkit.org/bukkit-plugins/kataparty/

commands:
  KataParty:
    description: "Display info about KataParty"
    usage: "/kataparty"
    permission: KataParty.info
    permission-message: "missing-commnd-perm.info"
    aliases:
      - kp
      - kpi
      - kpinfo
      - kpv
      - kpver
      - kpversion
      - kata
      - katatunka
      - katatunkaparty
      - party
      - partychat
      - pc
  kptoggle:
    description: "Toggle chat filtering between your party and global chat"
    usage: "/kptoggle"
    permission: KataParty.toggle
    permission-message: "missing-commnd-perm.toggle"
  kpcreate:
    description: "Create a KataParty via GUI"
    usage: "/kpcreate <KataParty-name>"
    permission: KataParty.create
    permission-message: "missing-commnd-perm.create"
  kplist:
    description: "Show a GUI with a list of available KataParties"
    usage: "/kplist"
    permission: KataParty.list
    permission-message: "missing-commnd-perm.list"
  kpjoin:
    description: "Join a KataParty by name instead of via /kplist"
    usage: "/kpjoin <KataParty-name>"
    permission: KataParty.join
    permission-message: "missing-commnd-perm.join"
  kpmanage:
    description: "Manage your personal KataParty settings, or the party-wide settings"
    usage: "/kpmanage"
    permission: KataParty.manage
    permission-message: "missing-commnd-perm.manage"
  kptp:
    description: "Teleport to someone in your KataParty via GUI or username"
    usage: "/kptp [optional-username]"
    permission: KataParty.teleport.do
    permission-message: "missing-commnd-perm.tp"
  kpshare:
    description: "Open the shared inventory for your KataParty"
    usage: "/kpshare"
    permission: KataParty.inventory.use
    permission-message: "missing-commnd-perm.share"
  kpleave:
    description: "Leave the KataParty you are in instead of via /kpmanage"
    usage: "/kpleave"
    permission: KataParty.leave
    permission-message: "missing-commnd-perm.leave"
  kpdisband:
    description: "Disband your KataParty instead of via /kpmanage"
    usage: "/kpdisband"
    permission: KataParty.disband
    permission-message: "missing-commnd-perm.disband"
  kpclose:
    description: "Force a KataParty to close (for admins)"
    usage: "/kpclose <KataParty-name>"
    permission: KataParty.close
    permission-message: "missing-commnd-perm.close"
  kpadmin:
    description: "Manage a specific KataParty's settings (for admins)"
    usage: "/kpadmin <KataParty-name>"
    permission: KataParty.admin
    permission-message: "missing-commnd-perm.admin"
  kpreload:
    description: "Reload and regenerate the config file"
    usage: "/kpreload"
    permission: KataParty.reload
    permission-message: "missing-commnd-perm.reload"

permissions:
  KataParty.*:
    description: "Gives access to all KataParty permissions (for admins)"
    children:
      KataParty.info: true
      KataParty.toggle: true
      KataParty.create: true
      KataParty.hide: true
      KataParty.seehidden: true
      KataParty.list: true
      KataParty.join: true
      KataParty.leave: true
      KataParty.disband: true
      KataParty.manage: true
      KataParty.admin: true
      KataParty.reload: true
      KataParty.teleport.*: true
      KataParty.inventory.*: true
      KataParty.invite.*: true
    default: op
  KataParty.teleport.*:
    description: "Gives access to all teleportation features"
    children:
      KataParty.teleport.do: true
      KataParty.teleport.disallow: true
      KataParty.teleport.disable: true
  KataParty.inventory.*:
    description: "Gives access to all inventory features"
    children:
      KataParty.inventory.use: true
      KataParty.inventory.enable: true
  KataParty.invite.*:
    description: "Gives access to all invitiation ticket permissions"
    children:
      KataParty.invite.enforce: true
      KataParty.invite.create: true
      KataParty.invite.accept: true
  KataParty.info:
    description: "See version/author infrmation about KataParty"
    default: true
  KataParty.toggle:
    description: "Toggle chat filtering for one's self"
    default: true
  KataParty.create:
    description: "Allows creation of a KataParty"
    default: true
  KataParty.hide:
    description: "Allows for hiding KataParties from the list"
    default: op
  KataParty.seehidden:
    description: "Allows for seeing hidden KataParties in the list"
    default: op
  KataParty.list:
    description: "Allows viewing a list of KataParties"
    default: true
  KataParty.join:
    description: "Allows joining a KataParty"
    default: true
  KataParty.disband:
    description: "Allows closing of a KataParty by party admin"
    default: true
  KataParty.manage:
    description: "Allows management of a KataParty (features based on party rank)"
    default: true
  KataParty.admin:
    description: "Allows management of a KataParty bypassing party rank"
    default: op
  KataParty.teleport.do:
    description: "Allows teleporting to a willing KataParty member"
    default: true
  KataParty.teleport.disallow:
    description: "Allows preventing other KataParty members from teleporting to you"
    default: true
  KataParty.teleport.disable:
    description: "Allows disabling teleportaion for an entire KataParty (based on party rank or KataParty.admin)"
    default: true
  KataParty.inventory.use:
    description: "Allows access to the shared KataParty inventory"
    default: true
  KataParty.inventory.enable:
    description: "Allows enabling/disabling the shared KataParty inventory"
    default: op
  KataParty.invite.enforce:
    description: "Allows making a party invite-only"
    default: true
  KataParty.invite.create:
    description: "Allows creating invitation tickets"
    default: true
  KataParty.invite.accept:
    description: "Allows accepting invitation tickets"
    default: true
  KataParty.reload:
    description: "Allows use of the /kpreload command to reload and regenerate the config"
    default: op
