# This file contains the default values used to generate the config
# from the template when the existing config is missing nodes

auto-updater: true

party-defaults:
  teleports: true
  pvp: false
  inventory: false
  visible: true
  invite-only: false
  self-teleports: true

remove-empty-parties: true

chat-filtering:
    prefix-when-party-preferred: "&l{%1$s}&r "
    prefix-when-global-preferred: "&o{%1$s}&r "
    filtered-chat-format: "&7&o"
    swap-string: "!"
    defaults:
      on-party-create: party
      on-party-join: party
      on-join-server: global

messages:
  party-member-inform: "You are in KataParty &b%1$s&r"
  party-introvert-inform: "You &care not&r in a KataParty"
  party-already-exists: "There is &calready&r a KataParty named &b%1$s&r"
  party-does-not-exist: "No KataParty named &c%1$s&r"
  join-already-member: "You are &aalready&r a member of &b%1$s&r"
  party-join-invite-only-fail: "&b%1$s&r is &cinvite-only&r; request an &binvitiation ticket"
  not-in-party: "You &care not&r in &oany&r KataParty"
  missing-disband-permission: "You &cdo not&r have permission to disband your KataParty"
  party-teleports-disabled: "Your KataParty &cdoes not&r allow teleportations"
  member-teleported-to: "You were &bteleported&r to %1$s"
  member-teleported-from: "%1$s &bteleported&r to &oyou&r"
  member-teleport-disabled: "You &ccannot&r teleport to %1$s"
  player-not-member: "%1$s &cis not&r in your KataParty"
  player-not-found: "&cCould not&r find player \"%1$s\""
  shared-inventory-disabled: "Shared Inventory is &cdisabled&r for this KataParty"
  chat-filtering-toggled: "Chat filtering settings &btoggled&r"
  chat-filtering-party: "You talk in &bparty chat&r, start message &bwith \"%1$s\"&r to speak globally"
  chat-filtering-global: "You talk in &bglobal chat&r, start message &bwith \"%1$s\"&r to speak in party"
  chat-filtering-howto: "Use &b/kptoggle&r to change this preference"
  chat-filtering-alone: "You are &calone&r, use &b\"%1$s\"&r or &b/kptoggle&r to speak in global chat"
  create-gui-title: "Create KataParty &3%1$s&r"
  create-create: "&bClick&r to create with these settings"
  create-cancel: "&bClose&r this inventory screen to &ccancel&r"
  create-name-taken: "&cName taken: %1$s"
  create-cancelled: "Your KataParty &cwas not&r created because you &cclosed&r the GUI"
  manage-hint: "Use &b/kpmanage&r to edit your &bpersonal settings&r or &bparty-wide&r settings"
  manage-gui-title: "&3%1$s&r Settings"
  manage-click-to-change: "&bClick&r to change"
  manage-cannot-change: "&cYou cannot change this"
  manage-click-to-use: "&bClick&r to use"
  manage-cannot-use: "&cYou cannot use this"
  manage-your-rank: "&rYour rank: &l%1$s"
  manage-leave: "&bLeft click&r to &cleave&r this KataParty"
  manage-not-member: "&rYou &care not&r a member of this KataParty"
  manage-rename: "&bRight click&r to &brename&r this KataParty"
  manage-admin: "&rYou are managing this KataParty &bas a server admin&r"
  manage-members: "&rMembers &o(submenu)"
  manage-members-online: "&r%1$d/%2$d &aonline&r"
  manage-mods-online: "&r%1$d/%2$d &bmoderators&b &aonline"
  manage-admins-online: "&r%1$d/%2$d &badmins&b &aonline"
  manage-teleports-enabled: "&bTeleportation&r is &aenabled"
  manage-teleports-disabled: "&bTeleportation&r is &cdisabled"
  manage-pvp-enabled: "&bPvP&r is &aenabled"
  manage-pvp-disabled: "&bPvP&r is &cdisabled"
  manage-inventory-enabled: "&bShared inventory&r is &aenabled"
  manage-inventory-disabled: "&bShared inventory&r is &cdisabled"
  manage-visibility-enabled: "&aWill&r be visible in list"
  manage-visibility-disabled: "&cWill not&r be visible in list"
  manage-invites-enabled: "&rYour KataParty is &binvite-only"
  manage-invites-disabled: "&r&oAnyone&r can join your KataParty"
  manage-sticky-enabled: "&rThis &bKataParty&r will stick around with no members"
  manage-sticky-disabled: "&rThis &bKataParty&r will close when the last member leaves"
  manage-generate-ticket: "&rGenerate an &binvite ticket"
  manage-disband: "&cDisband&r your KataParty"
  manage-close: "&cClose&r this KataParty"
  manage-summon: "&bTeleport&r all players to &oyourself"
  manage-self-teleports-enabled: "&rMembers &aare&r allowed to &bteleport&r to you"
  manage-self-teleports-disabled: "&rMembers &care not&r allowed to &bteleport&r to you"
  rename-gui-title: "&bRename&r Party"
  rename-name-requirements: "&rParty name must be &bunique&r and &cnot&r contain spaces"
  members-gui-title: "Manage &3%1$s&r members"
  members-return: "&bClick&r to return to &bmanagement&r"
  members-missing-player-file: "&4(missing player file; unknown name)"
  members-yourself: "&r&o(that's you!)"
  members-rank: "&rRank: %1$s"
  members-promote-moderator: "&bLeft click&r to promote to moderator"
  members-demote-kick: "&bRight click&r to kick"
  members-promote-admin: "&bLeft click&r to promote to admin"
  members-demote-member: "&bRight click&r to demote to member"
  members-demote-moderator: "&bRight click&r to demote to moderator"
  members-online: "&rOnline: %1$b"
  members-teleports: "&rAllows TP: %1$b"
  members-alive: "&rAlive: %1$b"
  list-gui-title: "&3List&r of KataParties"
  list-invisible: "&r(invisible)"
  list-members-online: "&r%1$d/%2$d members &aonline&r"
  list-pvp: "&rPvP: %1$b"
  list-teleports: "&rTP: %1$b"
  list-inventory: "&rShared Inv: %1$b"
  list-invite-only: "&rInvite-only: %1$b"
  list-join: "&bLeft click&r to join &o(you will leave your current KataParty)"
  list-member: "&r&oYou&r are in &othis&r KataParty"
  list-admin: "&bRight click&r to administrate"
  teleport-gui-title: "&3Members&r in your KataParty"
  party-rename-inform: "Your KataParty was &brenamed&r from &n%1$s&r to &n%2$s&r"
  party-join-inform: "&n%1$s&r has &ajoined&r your KataParty"
  party-left-inform: "You have &cleft&r your KataParty"
  party-leave-inform: "&n%1$s&r has &cleft&r your KataParty"
  party-closed-on-leave-inform: "&b%1$s&r has &cclosed&r behind you"
  party-disband-inform: "Your KataParty was &cdisbanded&r"
  party-teleports-enabled-inform: "Teleportation has been &aenabled&r for your KataParty"
  party-teleports-disabled-inform: "Teleportation has been &cdisabled&r for your KataParty"
  party-pvp-enabled-inform: "PvP has been &aenabled&r for your KataParty"
  party-pvp-disabled-inform: "PvP has been &cdisabled&r for your KataParty"
  party-visibility-enabled-inform: "Visibility has been &aenabled&r for your KataParty"
  party-visibility-disabled-inform: "Visibility has been &cdisabled&r for your KataParty"
  party-inventory-gui-title: "&b%1$s&r Shared Inventory"
  party-inventory-enable-inform: "Shared Inventory has been &aenabled&r for your KataParty"
  party-inventory-disable-inform: "Shared Inventory has been &cdisabled&r for your KataParty"
  party-invite-only-inform: "Your KataParty has been made &binvite only"
  party-public-inform: "Your KataParty has been made &bopen for anyone to join"
  party-shared-health-xp-enable-inform: "Shared Health + XP Gain has been &aenabled&r for your KataParty"
  party-shared-health-xp-disable-inform: "Shared Health + XP Gain has been &cdisabled&r for your KataParty"
  party-smart-potions-enable-inform: "Smart Potions has been &aenabled&r for your KataParty"
  party-smart-potions-disable-inform: "Smart Potions has been &cdisabled&r for your KataParty"
  party-rank-inform: "Your &brank&r has been set to &b%1$s&r"
  party-rank-admin: "Admin"
  party-rank-moderator: "Moderator"
  party-rank-member: "Member"
  party-self-teleports-enable-inform: "Teleportation has been personally &aenabled&r for you"
  party-self-teleports-disable-inform: "Teleportation has been personally &cdisabled&r for you"
  ticket-name: "&bKataParty Invitation Ticket"
  ticket-giver-instructions-1: "&bThrow&r this to the player you want to &binvite"
  ticket-giver-instructions-2: "&bRight click&r to &cdispose&r of this ticket"
  ticket-receive-inform: "You received an &binvitation ticket&r to KataParty &b%1$s"
  ticket-receiver-instructions-1: "&bRight click&r to &aaccept&r this &binvitation ticket"
  ticket-receiver-instructions-2: "&bThrow&r this out of your inventory to &creject"
  ticket-reject-inform: "You &crejected&r the &binvitation ticket&r for &b%1$s&r"
  ticket-accept-inform: "You &aaccepted&r the &binvitation ticket&r for &b%1$s&r"
  ticket-reject-inform-members: "%1$s has &crejected&r the &binvitation ticket&r for your KataParty"

version: 0
