# This file contains the default values used to generate the config
# from the template when the existing config is missing nodes

chat-filtering-swap: "!"

party-defaults:
  teleports: true
  pvp: false
  inventory: false
  visible: true
  self-teleports: true

remove-empty-parties: true

messages:
  party-member-inform: "You are in KataParty &n%1$s&r"
  party-introvert-inform: "You are &nnot&r in a KataParty"
  party-already-exists: "There is already a KataParty named %1$s"
  party-does-not-exist: "No KataParty named %1$s"
  not-in-party: "You are not in any KataParty"
  missing-disband-permission: "You do not have permission to disband your KataParty"
  party-teleports-disabled: "Your KataParty does not allow teleportations"
  member-teleported-to: "You were teleported to %1$s"
  member-teleported-from: "%1$s telepoted to you"
  member-teleport-disabled: "You cannot teleport to %1$s"
  player-not-member: "%1$s is not in your KataParty"
  player-not-found: "Could not find player \"%1$s\""
  shared-inventory-disabled: "Shared Inventory is disabled for this KataParty"
  chat-filtering-toggled: "Chat filtering settings toggled"
  chat-filtering-party: "You talk in party chat, start message with \"%1$s\" to speak globally"
  chat-filtering-global: "You talk in global chat, start message with \"%1$s\" to speak in party"
  create-gui-title: "Create KataParty %1$s"
  create-create: "Click to create with these settings"
  create-cancel: "Close this inventory screen to cancel"
  create-name-taken: "Name taken: %1$s"
  manage-gui-title: "%1$s Settings"
  manage-click-to-change: "Click to change"
  manage-cannot-change: "You cannot change this"
  manage-click-to-use: "Click to use"
  manage-cannot-use: "You cannot use this"
  manage-your-rank: "Your rank: %1$s"
  manage-leave: "Left click to leave this KataParty"
  manage-not-member: "You are not a member of this KataParty"
  manage-rename: "Right click to rename this KataParty"
  manage-admin: "You are managing this KataParty as a server admin"
  manage-members: "Members (submenu)"
  manage-members-online: "%1$d/%2$d online"
  manage-mods-online: "%1$d/%2$d moderators online"
  manage-admins-online: "%1$d/%2$d admins online"
  manage-teleports-enabled: "Teleportation enabled"
  manage-teleports-disabled: "Teleportation disabled"
  manage-pvp-enabled: "PvP enabled"
  manage-pvp-disabled: "PvP disabled"
  manage-inventory-enabled: "Shared inventory enabled"
  manage-inventory-disabled: "Shared inventory disabled"
  manage-visibility-enabled: "Will be visible in list"
  manage-visibility-disabled: "Will not be visible in list"
  manage-disband: "Disband your KataParty"
  manage-close: "Close this KataParty"
  manage-summon: "Teleport all players to yourself"
  manage-self-teleports-enabled: "Members are allowed to teleport to you"
  manage-self-teleports-disabled: "Members are not allowed to teleport to you"
  rename-gui-title: "Rename Party"
  rename-name-requirements: "Party name must be unique and not contain spaces"
  members-gui-title: "Manage %1$s members"
  members-return: "Click to return to management"
  members-missing-player-file: "&4(missing player file; unknown name)"
  members-yourself: "(that's you!)"
  members-rank: "Rank: %1$s"
  members-promote-moderator: "Left click to promote to moderator"
  members-demote-kick: "Right click to kick"
  members-promote-admin: "Left click to promote to admin"
  members-demote-member: "Right click to demote to member"
  members-demote-moderator: "Right click to demote to moderator"
  members-online: "Online: %1$b"
  members-teleports: "Allows TP: %1$b"
  members-alive: "Alive: %1$b"
  list-gui-title: "List of KataParties"
  list-invisible: "(invisible)"
  list-members-online: "%1$d/%2$d members online"
  list-pvp: "PvP: %1$b"
  list-teleports: "TP: %1$b"
  list-inventory: "Shared Inv: %1$b"
  list-join: "Left click to join (you will leave your current KataParty)"
  list-member: "You are in this KataParty"
  list-admin: "Right click to administrate"
  teleport-gui-title: "Members in your KataParty"
  party-rename-inform: "Your KataParty was renamed from &n%1$s&r to &n%2$s&r"
  party-join-inform: "&n%1$s&r has joined your KataParty"
  party-left-inform: "You have left your KataParty"
  party-leave-inform: "&n%1$s&r has left your KataParty"
  party-teleports-enabled-inform: "Teleportation has been &nenabled&r for your KataParty"
  party-teleports-disabled-inform: "Teleportation has been &ndisabled&r for your KataParty"
  party-pvp-enabled-inform: "PvP has been &nenabled&r for your KataParty"
  party-pvp-disabled-inform: "PvP has been &ndisabled&r for your KataParty"
  party-visibility-enabled-inform: "Visibility has been &nenabled&r for your KataParty"
  party-visibility-disabled-inform: "Visibility has been &ndisabled&r for your KataParty"
  party-inventory-gui-title: "%1$s Shared Inventory"
  party-inventory-enable-inform: "Shared Inventory has been &nenabled&r for your KataParty"
  party-inventory-disable-inform: "Shared Inventory has been &ndisabled&r for your KataParty"
  party-disband-inform: "Your KataParty was disbanded"
  party-shared-health-xp-enable-inform: "Shared Health + XP Gain has been &nenabled&r for your KataParty"
  party-shared-health-xp-disable-inform: "Shared Health + XP Gain has been &ndisabled&r for your KataParty"
  party-smart-potions-enable-inform: "Smart Potions has been &nenabled&r for your KataParty"
  party-smart-potions-disable-inform: "Smart Potions has been &ndisabled&r for your KataParty"
  party-rank-inform: "Your rank has been set to &n%1$s&r"
  party-rank-admin: "Admin"
  party-rank-moderator: "Moderator"
  party-rank-member: "Member"
  party-self-teleports-enable-inform: "Teleportation has been personally &nenabled&r for you"
  party-self-teleports-disable-inform: "Teleportation has been personally &ndisabled&r for you"

version: 0
