# KataParty Configuration, generated/updated by v${project.version}

# If you want to reset any setting to default, simply delete it or
# comment it out and the next time the config is reloaded, this file
# will be re-generated keeping your existing settings and defaulting
# any missing settings. Any comments you make are erased, however.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Notice! EventFilterServices is a required plugin dependency!  #
# You must have it installed for this plugin to work properly!  #
# http://dev.bukkit.org/bukkit-plugins/eventfilter/             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Set this to false to disable use of Gravity's Updater
# http://forums.bukkit.org/threads/Gravity-Updater.96681/
auto-updater: [%auto-updater%]

# If set to true, this plugin will try to use TagAPI to color
# nametags for party members. For this feature to work you must
# have installed TagAPI:
# http://dev.bukkit.org/bukkit-plugins/tag/
color-nametags: [%color-nametags%]

# Here, you can change the default settings for newly created parties.
# Some settings require permission nodes to be changed.
party-defaults:
  # Teleportation for whole party
  teleports: [%party-defaults.teleports%]
  # PvP amongst party members
  pvp: [%party-defaults.pvp%]
  # Shared inventory for party
  inventory: [%party-defaults.inventory%]
  # Party visibility in list
  visible: [%party-defaults.visible%]
  # Whether party requires an invitation ticket to join
  invite-only: [%party-defaults.invite-only%]
  # Whether party members share the same health bar
  shared-health: [%party-defaults.shared-health%]
  # Teleportation setting for individual party members
  self-teleports: [%party-defaults.self-teleports%]

# This is the number of rows in party shared inventories.
# Values above 6 will not display properly to clients.
shared-inventory-rows: [%shared-inventory-rows%]

# Set to true to have empty parties automatically be disbanded. If
# you want to instead keep empty parties, set to false instead.
remove-empty-parties: [%remove-empty-parties%]

# Distributes experience gain among party members
share-xp-gain: [%share-xp-gain%]

# Makes potions smart when PvP is disabled within a party
smart-splash-potions: [%smart-splash-potions%]

# This allows you to control the grace periods on the /kpback
# command for various permission nodes. Each sub-node here is
# appended to the string "KataParty.back.grace-periods." to check
# if the player has that particular permission. The longest
# timeout is used. If a player tries to use the /kpback command
# after the grace period has ended, the command will fail. The
# unit of measurement for grace periods is ticks/second - note
# there are 20 ticks per second in vanilla Minecraft. 1200 ticks
# is 1 minute. If you use -1 the grace period will be infinite.
back-command-grace-periods: [%back-command-grace-periods%]

# The number of ticks a player must wait before being allowed
# to rejoin a party they were kicked from. Set to -1 to make
# kicks act like bans. This timeout can be reset for a player
# with the /kppardon command.
party-kick-timeout: [%party-kick-timeout%]

# Here you can configure the formatting used for chat filtering
chat-filtering:
  # This is the prefix to use for party messages when the
  # receiver prefers party chat
  prefix-when-party-preferred: [%chat-filtering.prefix-when-party-preferred%]
  # This is the prefix to use for party messages when the
  # receiever prefers global chat
  prefix-when-global-preferred: [%chat-filtering.prefix-when-global-preferred%]
  # This is the prefix to use after username and before chat
  # message for chat coming from the non-preferred source
  filtered-chat-format: [%chat-filtering.filtered-chat-format%]
  # This is what should be at the start of a message to send to the
  # opposite chat; global instead of party or vice-versa.
  swap-string: [%chat-filtering.swap-string%]
  # Here you can change the default preferred chat in certain cases
  # Only valid strings are "party" and "global"
  defaults:
    # Just after creating a new party
    on-party-create: [%chat-filtering.defaults.on-party-create%]
    # Just after joining an existing party
    on-party-join: [%chat-filtering.defaults.on-party-join%]
    # Just after joining the server while in a party
    on-join-server: [%chat-filtering.defaults.on-join-server%]

# Below, you can customize the messages that are sent/shown to players.
messages: [%messages%]

# If you're a developer (or just curious), then set this to true for colorful console spam.
debug: [%debug%]

# This is updated automatically. Don't change it. Java will smite you if you do.
this-is-the-config-version-number-dont-change-it-unless-you-want-very-bad-things-to-happen: [%version%]
